config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resource :like, only: [:create]
    resource :retweet, only: [:create]
  end
  root to: "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true

  # after_create_commit { broadcast_prepend_to "tweets" }
  # after_destroy_commit { broadcast_remove_to "tweets" }
  broadcasts_to ->(tweet) { :tweets }, inserts_by: :prepend, target: "tweets"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @tweet.increment!(:likes).save
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/tweet", locals: { tweet: @tweet}) }
      @tweets = Tweet.all.order(created_at: :desc)
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :set_tweet

  def create
    @tweet.increment!(:retweets).save
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/tweet", locals: { tweet: @tweet}) }
      @tweets = Tweet.all.order(created_at: :desc)
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet}) }
        @tweets = Tweet.all.order(created_at: :desc)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweets_url, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet}) }
        @tweets = Tweet.all.order(created_at: :desc)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@tweet) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :likes, :retweets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Tweets</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
        crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <%= turbo_include_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/tweets/_form.html.erb
<div class="card card-body" id="<%= dom_id(tweet) %>">
  <%= form_with(model: tweet, id: dom_id(tweet)) do |form| %>
    <% if tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <div class="action">
      <%= form.submit class: "btn btn-sm btn-outline-success" %>
      <%= link_to "Cancel", @tweet, class: "btn btn-sm btn-outline-danger" %>
    </div>
  <% end %>
</div>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet) do %>
<div class="card card-body" id="<%= dom_id(tweet) %>">
    <div><%= tweet.body %></div>

    <div class="mt-2">
      <%= link_to "Like (#{tweet.likes})",
                  tweet_like_path(tweet),
                  method: :post,
                  class: "btn btn-sm btn-outline-success" %>

      <%= link_to "Retweet (#{tweet.retweets})",
                  tweet_retweet_path(tweet),
                  method: :post,
                  class: "btn btn-sm btn-outline-info" %>

      <%= link_to 'Edit', edit_tweet_path(tweet),
                  class: "btn btn-sm btn-outline-primary" %>

      <%= link_to 'Destroy', tweet_path(tweet), method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: "btn btn-sm btn-outline-danger" %>
    </div>
</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= turbo_frame_tag dom_id(@tweet) do %>
  <%= render 'form', tweet: @tweet %>
<% end %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<%= turbo_stream_from "tweets" %>
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<h4>New Tweet</h4>

<%= turbo_frame_tag "tweet-form" do %>
  <%= render "tweets/form", tweet: @tweet %>
<% end %>

<h4>Tweet Feed</h4>

<%= turbo_frame_tag "tweets" do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<%= render @tweet %>